### ISSUE TITLE
There is very little probability that `schedule_task` would execute twice.

### ISSUE THREAD

**Issue by starccy** [patrick-fitzgerald/actix-web-cron-example#1]
Hi,
First of all, thanks for your example, it's very helpful for my project.
But I find there may a little problem when computing the next cron time:

https://github.com/patrick-fitzgerald/actix-web-cron-example/blob/3ccc9832dab73ac5a244b703e62b0e81f4fc1635/src/scheduler.rs#L42-L43

I have no idea why need to cast to milliseconds here: `Duration::from_millis(duration_until.num_milliseconds() as u64)`.    
I think it will lose precision for micro / nano seconds and cause the logic will be executed a few microseconds ahead of time(0.xxx ms).

I don't know if I make it clear but I can give an example:     
Imagine I have a cron job run task every five seconds: `0/5  *  *  *  *  *  *`.    
And now time is: `2021-02-25T12:00:01.999001`, So next cron time is: `2021-02-25T12:00:05:000000`, and diff seconds is: `3.000999 s`.   
However, only milliseconds part will be reserved, so it will sleep only 3.00s.   
The actual time it will be executed is `2021-02-25T12:00:04.999001`. Then computing next cron time which is still `2021-02-25T12:00:05:000000`. So the task will be executed immediately once again.

**Comment by patrick-fitzgerald** [comment]
Thanks for the feedback @starccy . I'll look into this!

**Comment by patrick-fitzgerald** [comment]
PR's are welcome too 🙂

**Comment by starccy** [comment]
The solution is quiet simple: just use `.to_std()` from `chrono::Duration` to convert itself to `std::time::Duration`.  
 I'd like to send a PR.
